cart:
  fullnameOverride: carts

  app:
    persistence:
      provider: dynamodb

    dynamodb:
      tableName: Items
      createTable: false

catalog:
  fullnameOverride: catalog

checkout:
  fullnameOverride: checkout

orders:
  fullnameOverride: orders

ui:
  fullnameOverride: ui

  app:
    endpoints:
      catalog: http://catalog:80
      carts: http://carts:80
      checkout: http://checkout:80
      orders: http://orders:80
